### PR TITLE
fix: sveltekit version and custom service worker injection point (js)

### PR DESCRIPTION
**Pull request by userquin**
### Description

Use `/` as navigate fallback in custom VanillaJS service workers.

This PR also includes:
- update `@vite-pwa/sveltekit` dependency version fixing a problem with `fast-glob` (replaced with `tinyglobby`): https://github.com/vite-pwa/sveltekit/pull/92
- update pnpm to 9.12.2.

### Additional Context

check #25

---

> [!TIP]
> The author of this PR can publish a _preview release_ by commenting `/publish` below.

### CODE REVIEW

**Comment by alexander-vidoni** [comment]
Thank you.

**Comment by userquin** [comment]
> Thank you.

Svelte projects using Vite and so we'll have `index.html` entry point, there is no need to change the corresponding sw.

**Comment by alexander-vidoni** [comment]
> Svelte projects using Vite and so we'll have `index.html` entry point, there is no need to change the corresponding sw.

Hi, 
i did a lot of testing today and i think we are both correct.

**@userquin perspective:** 

Yes, there is an _index.html_ if you call` /index.html` in the brower or cURL etc.
It ships the same content as if you request just ` / `
But these `index.html` and ` / ` are only aliases of the applications entrypoint.

**@alexander-vidoni perspective**

The shipped content of `index.html` and ` / ` are **no assets**, they are _entrypoints_.

If you are building a `sveltekit application` with `vite` erverything is fine.

But if you scaffold your `sveltekit application` with `create vite-pwa` **and** the `vite-pwa-plugin` as its dependency you introduce `workbox` functionality and the `precaching code` to the `service-worker.js` file in the `/src` directory.

When using the `injectManifest` option, the build process replaces the `self.__WB_MANIFEST` placeholder with an array of urls and hashes to the parameters of the `precacheAndRoute() `function.

This `array` of urls in the service-worker was **hardcoded** by the build process and and was injected into the service-worker code.

### The **problem** or better the **bug**

During build time there is no `index.html` file to `glob`, because index.html is not a physical file,  it is an _alias_ to the _applications entrypoint_.

The consequence is, that during runtime in the browser, the service-worker runs prechacheAndRoute() with an array which **does not** contain `index.html`.

If `index.html `is **not** cached, the route to `index.html ` could **not** be registered 

```
// to allow work offline
registerRoute(new NavigationRoute(
  createHandlerBoundToURL('/index.html'),
  { allowlist },
))
```
and the `service-worker.js` throws an [exception](url) which is **not** caught:

```
service-worker.js:2 Uncaught non-precached-url: non-precached-url :: [{"url":"index.html"}]
    at Q.createHandlerBoundToURL (http://localhost:4173/service-worker.js:2:1255)
    at re (http://localhost:4173/service-worker.js:2:5578)
    at http://localhost:4173/service-worker.js:2:7769
```

The uncaught exception leads to a `#redundant` state during service-worker.js installation in the browser, because faulty service-worker will not be activated by the browser.

The glob during build does fail (does not include index.html), due to the nonexistence of a **physical** index.html in the directories.
As user of create-pwa you alwas have a service-worker which fails, which leads to a non installable webapp, which leads to frustration, which leads to not using that `fantasic build stack` you maintain.

Thank you for your work.

**Comment by userquin** [comment]
You cannot use `vite-plugin-pwa` with kit, you need to use kit pwa integration plugin: this plugin will replace the `index.html` with the `/` mapping (used by `create-pwa` when selecting Svelte + Kit).

If you're using offline support (precaching) with kit, then you need to prerender at least one page, otherwise you cannot use precaching.

Anyway, you can change everything in the pwa options and so there is no problem at all.

About workbox (workbox-build): it will be used if you enable it, that's, when using `generateSW` strategy or using `injectManifest` with offline and precaching support (`injectionPoint`), otherwise workbox-build won't be even loaded.

**Pull request merged**
