### PR TITLE
Origin/alexander vidoni/fix missing dependency

### PR DESCRIPTION
**Pull request by alexander-vidoni**
### Description

This PR fixes two bugs:

1) ADD a missing dependency fast-glob to package.json
2) FIX a typo in six files which make the the service-worker.js failing during installation in the browser.

/publish

### CODE REVIEW

**Comment by userquin** [comment]
We don't use `fast-glob`, replaced with `tinyglobby`, why is this dependency needed?

**Comment by alexander-vidoni** [comment]
When running `npm run build` in the created sveltekit project folder the missing of fast-glob exits with a fatal error.

How to replay:

**CREATE**

npm create @vite-pwa/pwa@latest
✔ Project name: … vite-project
✔ Select a framework: › Svelte
✔ Select a variant: › SvelteKit ↗
✔ PWA Name: … vite-project
✔ PWA Short Name: … vite-project
✔ PWA Description: … 
✔ Theme color: … #ffffff
✔ Select a strategy: › injectManifest
✔ Select a behavior: › Auto update
✔ Enable periodic SW updates? … no / yes
✔ Show offline ready prompt? … no / yes
✔ Generate PWA Assets Icons on the fly? … no / yes

create-svelte version 6.4.0

┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  No
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!

Install more integrations with:
  npx svelte-add

Next steps:
  1: cd vite-project
  2: npm install
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat


PWA configuration done. Now run:

  cd vite-project
  npm install
  npm run dev


**INSTALL**

npm install
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 434 packages, and audited 435 packages in 23s

91 packages are looking for funding
  run `npm fund` for details

4 low severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**BUILD**

npm run build

> vite-project@0.0.1 build
> vite build

**ERROR**

npm run build

> vite-project@0.0.1 build
> vite build

failed to load config from [...] vite-project/vite.config.js
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fast-glob' imported from [...] vite-project/node_modules/@vite-pwa/sveltekit/dist/index.mjs

**FIX**

npm i fast-glob

**Comment by alexander-vidoni** [comment]
> We don't use `fast-glob`, replaced with `tinyglobby`, why is this dependency needed?

Yes, but not in version `2.0.0` of `unbuild`.

The change from `fast-glob` to `tinyglobby` takes place first in `unbuild v3.0.0-rc.8`.

**Comment by userquin** [comment]
Looks like we've some problem in the kit integration...

**Comment by userquin** [comment]
This line shouldn't be there: https://github.com/vite-pwa/sveltekit/blob/4cc62f598483173775308a143df5da9a13450bb0/src/plugins/SvelteKitPlugin.ts#L7

**Comment by alexander-vidoni** [comment]
I edited my post look at: https://github.com/vite-pwa/create-pwa/pull/25#issuecomment-2423357674

**Comment by alexander-vidoni** [comment]
I tested building `sveltekit` with `unbuild v3.0.0.rc8`  and then there is no more `fast-glob `in the build of `sveltekit`.

**Comment by userquin** [comment]
This is a dev dependency in kit repo for runtime not for build, tinyglobby is external when building the distro, the problem is about the `@ts-expect-error`  there is no dependency in the package.json.

I'll release a new patch version... then we can just update the version here and remove `fast-glob` also from this PR.

**Comment by userquin** [comment]
@alexander-vidoni can you check with https://github.com/vite-pwa/sveltekit/pull/92#issuecomment-2423391662 ?

**Comment by alexander-vidoni** [comment]
@userquin it's working in my szenario. Thank you for you help!

**Comment by userquin** [comment]
@alexander-vidoni can you remove fast-glob from this PR? I'm finish testing and will release a patch, then we can just update the dependencies here or in another PR

**Comment by userquin** [comment]
ok, the `generatesSW` strategy is fine inthis repo

**Comment by userquin** [comment]
why do you close this PR? It will fix the navigate fallback.

**Comment by alexander-vidoni** [comment]
> why do you close this PR? It will fix the navigate fallback.

Sorry, it's my first time trying to contribute to a project. i did not really know what i am doing. Sorry for that.

**Pull request closed without merging**
